#!/usr/bin/env bash

[[ "${DOCKER_TAG}" == "latest" ]] && \
    { echo 'qemu-user-static: Download not required for this arch'; exit 0; }

TAGS_API="https://api.github.com/repos/multiarch/qemu-user-static/tags"
URL="https://github.com/multiarch/qemu-user-static/releases/download"
LATEST_TAG=$(curl -Ls $TAGS_API | \
            awk -F'"' '/name.*v[0-9]/ {print $4; exit}')
ARCH=$([[ "${DOCKER_TAG}" == "armhf" ]] && \
            echo "${DOCKER_TAG::-2}" || echo "${DOCKER_TAG}")

curl -Ls "${URL}/${LATEST_TAG}/x86_64_qemu-${ARCH}-static.tar.gz" | \
            tar xzv