#!/usr/bin/env bash
env
set -x

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d'.' -f2)

[ "${BUILD_ARCH}" == "Dockerfile" ] && \
    { echo 'qemu-user-static: Download not required for this arch'; exit 0; }

TAGS_API="https://api.github.com/repos/multiarch/qemu-user-static/tags"
URL="https://github.com/multiarch/qemu-user-static/releases/download"
LATEST_TAG=$(curl -Ls $TAGS_API | \
            awk -F'"' '/name.*v[0-9]/ {print $4; exit}')
STATIC_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && \
            echo "${BUILD_ARCH::-2}" || echo "${BUILD_ARCH}")

curl -Ls "${URL}/${LATEST_TAG}/x86_64_qemu-${STATIC_ARCH}-static.tar.gz" | \
            tar xzv