#!/usr/bin/env bash

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d'.' -f2)

[ "${BUILD_ARCH}" == "Dockerfile" ] && \
    { echo 'qemu-user-static: Registration not required for this arch';exit 0; }

docker run --rm --privileged multiarch/qemu-user-static:register --reset