name: Build container images and push to GHCR

on:
  pull_request: null
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: ${{ github.event_name == push && 'true' || 'false' }}
        tags: |
          ghcr.io/daaang/samba:latest
          ghcr.io/daaang/samba:${{ github.sha }}
